clc;
close all;
format long;
PI=180.0;
S=5.8*10^7;
C=3.8*10^8;
U=0.0032;
J=sqrt(-1);
L=input ('\n length of dipole= ');
r=input ('radius of dipole= ');
Y=input ('wavelength of dipole= ');
f=C/Y;
ratio=L/Y;
rloss=L/(6*PI*r)*sqrt((PI*f*U)/2*r);
rrad=20*PI^2*(L/Y)^2;
if ratio<=0.1
disp('it is a short dipole\n');
aem=3/(8*PI)*Y^2;
D=4*PI/(Y^2)*aem;
K=rrad/(rrad+rloss);
G=K*D;
else
disp('it is a dipole\n');
aem=30/(73*PI)*Y^2;
D=4*PI/(Y^2)*aem;
K=rrad/(rrad+rloss);
G=K*D;
end;
Db=10*log10(D);
Bw = 4 * PI / D;
fprintf('\n input parameters:\n ');
fprintf('\n length of dipole in wavelength=%6.4f',L);
fprintf('\n radius of dipole in wavelength=%6.4f',r);
fprintf('\n wavelength of dipole=%6.4f',Y);
fprintf('\n output parameters:\n ');
fprintf('\n directivity=%6.4f',D);
fprintf('\n directivity(Db)=%6.4f',Db);
fprintf('\n Beam width angle=%10.4f',Bw);
fprintf('\n Gain=%10.4f',G);