clc;
close all;
Y=input ('wavelength of dipole= ');
k=input('constant value ranging from 0.5 to 0.7 ');
a=10*Y;
A0=a^2;
D=((4*pi)/Y^2)*A0*k;
fprintf('\n input parameters:\n ');
fprintf('\n wavelength of dipole=%6.4f',Y);
fprintf('\n output parameters:\n ');
fprintf('\n directivity=%6.4f',D);